var countrys = {
			"United States" :	"United States",
			"United Kingdom" :	"United Kingdom",
			"Canada" :	"Canada",
			"Australia" :	"Australia",
			"Albania" :	"Albania",
			"Algeria" :	"Algeria",
			"American Samoa" :	"American Samoa",
			"Andorra" :	"Andorra",
			"Angola" :	"Angola",
			"Anguilla" :	"Anguilla",
			"Antarctica" :	"Antarctica",
			"Antigua And Barbuda" :	"Antigua And Barbuda",
			"Argentina" :	"Argentina",
			"Armenia" :	"Armenia",
			"Aruba" :	"Aruba",
			"Australia" :	"Australia",
			"Austria" :	"Austria",
			"Azerbaijan" :	"Azerbaijan",
			"Bahamas" :	"Bahamas",
			"Bahrain" :	"Bahrain",
			"Bangladesh" :	"Bangladesh",
			"Barbados" :	"Barbados",
			"Belarus" :	"Belarus",
			"Belgium" :	"Belgium",
			"Belize" :	"Belize",
			"Benin" :	"Benin",
			"Bermuda" :	"Bermuda",
			"Bhutan" :	"Bhutan",
			"BO" :	"Bolivia",
			"Bosnia And Herzegovina" :	"Bosnia And Herzegovina",
			"Botswana" :	"Botswana",
			"Bouvet Island" :	"Bouvet Island",
			"Brazil" :	"Brazil",
			"British Indian Ocean Territory" :	"British Indian Ocean Territory",
			"Brunei Darussalam" :	"Brunei Darussalam",
			"Bulgaria" :	"Bulgaria",
			"Burkina Faso" :	"Burkina Faso",
			"Burundi" :	"Burundi",
			"Cambodia" :	"Cambodia",
			"Cameroon" :	"Cameroon",
			"Cape Verde" :	"Cape Verde",
			"Cayman Islands" :	"Cayman Islands",
			"Central African Republic" :	"Central African Republic",
			"Channel Islands" :	"Channel Islands",
			"Chad" : "Chad",
			"Chile" : "Chile",
			"China" :	"China",
			"Christmas Island" :	"Christmas Island",
			"Cocos (Keeling) Islands" :	"Cocos (Keeling) Islands",
			"Colombia" :	"Colombia",
			"Comoros" :	"Comoros",
			"Congo" :	"Congo",
			"Congo, The Dem. Rep. Of The" :	"Congo, The Dem. Rep. Of The",
			"Cook Islands" :	"Cook Islands",
			"Costa Rica" :	"Costa Rica",
			"Cote D'ivoire" :	"Cote D'ivoire",
			"Croatia" :	"Croatia",
			"Cyprus" :	"Cyprus",
			"Czech Republic" :	"Czech Republic",
			"Denmark" :	"Denmark",
			"Djibouti" :	"Djibouti",
			"Dominica" :	"Dominica",
			"Dominican Republic" :	"Dominican Republic",
			"East Timor" :	"East Timor",
			"Ecuador" :	"Ecuador",
			"Egypt" :	"Egypt",
			"El Salvador" :	"El Salvador",
			"Equatorial Guinea" :	"Equatorial Guinea",
			"Eritrea" :	"Eritrea",
			"Estonia" :	"Estonia",
			"Ethiopia" :	"Ethiopia",
			"Falkland Islands (Malvinas)" :	"Falkland Islands (Malvinas)",
			"Faroe Islands" :	"Faroe Islands",
			"Fiji" :	"Fiji",
			"Finland" :	"Finland",
			"France" :	"France",
			"French Guiana" :	"French Guiana",
			"French Polynesia" :	"French Polynesia",
			"French Southern Territories" :	"French Southern Territories",
			"Gabon" :	"Gabon",
			"Gambia" :	"Gambia",
			"Georgia" :	"Georgia",
			"Germany" :	"Germany",
			"Ghana" :	"Ghana",
			"Gibraltar" :	"Gibraltar",
			"Greece" :	"Greece",
			"Greenland" :	"Greenland",
			"Grenada" :	"Grenada",
			"Guadeloupe" :	"Guadeloupe",
			"Guam" :	"Guam",
			"Guatemala" :	"Guatemala",
			"Guinea" :	"Guinea",
			"Guinea-Bissau" :	"Guinea-Bissau",
			"Guyana" :	"Guyana",
			"Haiti" :	"Haiti",
			"Heard Island And Mcdonald Islands" :	"Heard Island And Mcdonald Islands",
			"Holy See (Vatican City State)" :	"Holy See (Vatican City State)",
			"Honduras" :	"Honduras",
			"Hong Kong" :	"Hong Kong",
			"Hungary" :	"Hungary",
			"Iceland" :	"Iceland",
			"India" :	"India",
			"Indonesia" :	"Indonesia",
			"Ireland" :	"Ireland",
			"Israel" :	"Israel",
			"Italy" :	"Italy",
			"Jamaica" :	"Jamaica",
			"Japan" :	"Japan",
			"Jordan" :	"Jordan",
			"Kazakstan" :	"Kazakstan",
			"Kenya" :	"Kenya",
			"Kiribati" :	"Kiribati",
			"Kuwait" :	"Kuwait",
			"Kyrgyzstan" :	"Kyrgyzstan",
			"Lao People's Democratic Republic" :	"Lao People's Democratic Republic",
			"Latvia" :	"Latvia",
			"Lebanon" :	"Lebanon",
			"Lesotho" :	"Lesotho",
			"Libya" :	"Libya",
			"Liechtenstein" :	"Liechtenstein",
			"Lithuania" :	"Lithuania",
			"Luxembourg" :	"Luxembourg",
			"Macau" :	"Macau",
			"Macedonia" :	"Macedonia",
			"Madagascar" :	"Madagascar",
			"Malawi" :	"Malawi",
			"Malaysia" :	"Malaysia",
			"Maldives" :	"Maldives",
			"Mali" :	"Mali",
			"Malta" :	"Malta",
			"Marshall Islands" :	"Marshall Islands",
			"Martinique" :	"Martinique",
			"Mauritania" :	"Mauritania",
			"Mauritius" :	"Mauritius",
			"Mayotte" :	"Mayotte",
			"Mexico" :	"Mexico",
			"Micronesia, Federated States Of" :	"Micronesia, Federated States Of",
			"Moldova, Republic Of" :	"Moldova, Republic Of",
			"Monaco" :	"Monaco",
			"Mongolia" :	"Mongolia",
			"Montserrat" :	"Montserrat",
			"Morocco" :	"Morocco",
			"Mozambique" :	"Mozambique",
			"Namibia" :	"Namibia",
			"Nauru" :	"Nauru",
			"Nepal" :	"Nepal",
			"Netherlands" : 	"Netherlands",
			"New Caledonia" :	"New Caledonia",
			"Netherlands Antilles" :	"Netherlands Antilles",
			"New Zealand" :	"New Zealand",
			"Nicaragua" :	"Nicaragua",
			"Niger" :	"Niger",
			"Nigeria" :	"Nigeria",
			"Niue" :	"Niue",
			"Norfolk Island" :	"Norfolk Island",
			"Northern Mariana Islands" :	"Northern Mariana Islands",
			"Norway" :	"Norway",
			"Oman" :	"Oman",
			"Pakistan" :	"Pakistan",
			"Palau" :	"Palau",
			"Palestinian Territory, Occupied" :	"Palestinian Territory, Occupied",
			"Panama" :	"Panama",
			"Papua New Guinea" :	"Papua New Guinea",
			"Paraguay" :	"Paraguay",
			"Peru" :	"Peru",
			"Philippines" :	"Philippines",
			"Pitcairn" :	"Pitcairn",
			"Poland" :	"Poland",
			"Portugal" :	"Portugal",
			"Puerto Rico" :	"Puerto Rico",
			"Qatar" :	"Qatar",
			"Reunion" :	"Reunion",
			"Romania" :	"Romania",
			"Russian Federation" :	"Russian Federation",
			"Rwanda" :	"Rwanda",
			"Saint Helena" :	"Saint Helena",
			"KNSaint Kitts And Nevis" :	"Saint Kitts And Nevis",
			"Saint Lucia" :	"Saint Lucia",
			"Saint Pierre And Miquelon" :	"Saint Pierre And Miquelon",
			"Saint Vincent And The Grenadines" :	"Saint Vincent And The Grenadines",
			"Samoa" :	"Samoa",
			"San Marino" :	"San Marino",
			"Sao Tome And Principe" :	"Sao Tome And Principe",
			"Saudi Arabia" :	"Saudi Arabia",
			"Senegal" :	"Senegal",
			"Seychelles" :	"Seychelles",
			"Singapore" :	"Singapore",
			"Slovakia" :	"Slovakia",
			"Slovenia" :	"Slovenia",
			"Solomon Islands" :	"Solomon Islands",
			"Somalia" :	"Somalia",
			"South Africa" :	"South Africa",
			"South Georgia / South Sandwich Islands" :	"South Georgia / South Sandwich Islands",
			"Spain" :	"Spain",
			"Sri Lanka" :	"Sri Lanka",
			"Suriname" :	"Suriname",
			"Svalbard And Jan Mayen" :	"Svalbard And Jan Mayen",
			"Swaziland" :	"Swaziland",
			"Sweden" :	"Sweden",
			"Switzerland" :	"Switzerland",
			"Syrian Arab Republic" :	"Syrian Arab Republic",
			"Taiwan" :	"Taiwan",
			"Tajikistan" :	"Tajikistan",
			"Tanzania, United Republic Of" :	"Tanzania, United Republic Of",
			"Thailand" :	"Thailand",
			"Togo" :	"Togo",
			"Tokelau" :	"Tokelau",
			"Tonga" :	"Tonga",
			"Trinidad And Tobago" :	"Trinidad And Tobago",
			"Tunisia" :	"Tunisia",
			"Turkey" :	"Turkey",
			"Turkmenistan" :	"Turkmenistan",
			"Turks And Caicos Islands" :	"Turks And Caicos Islands",
			"Tuvalu" :	"Tuvalu",
			"Uganda" :	"Uganda",
			"Ukraine" :	"Ukraine",
			"United Arab Emirates" :	"United Arab Emirates",
			"United States Minor Outlying Islands" :	"United States Minor Outlying Islands",
			"Uruguay" :	"Uruguay",
			"Uzbekistan" :	"Uzbekistan",
			"Vanuatu" :	"Vanuatu",
			"Venezuela" :	"Venezuela",
			"Viet Nam" :	"Viet Nam",
			"Virgin Islands, British" :	"Virgin Islands, British",
			"Virgin Islands, U.S." :	"Virgin Islands, U.S.",
			"Wallis And Futuna" :	"Wallis And Futuna",
			"Western Sahara" :	"Western Sahara",
			"Yemen" :	"Yemen",
			"Yugoslavia" :	"Yugoslavia",
			"Zambia" :	"Zambia"
			};

function printCountryOptions()
{
	for(key in countrys)
	{
		document.write('<option value="' + key + '">' +countrys[key] + '</option>');
	}
}
